---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/man-2814937_1920/man-2814937_1920.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/204681/master/file/figures/man-2814937_1920/man-2814937_1920.png"
    folder_url: "/users/87737/articles/204681/master/folder/figures/man-2814937_1920"
