---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2017-10-13 at 4-18-22 AM/Screen Shot 2017-10-13 at 4-18-22
      AM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/204681/master/file/figures/Screen%20Shot%202017-10-13%20at%204-18-22%20AM/Screen%20Shot%202017-10-13%20at%204-18-22%20AM.png"
