---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/key-96233_1920/key-96233_1920.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/204681/master/file/figures/key-96233_1920/key-96233_1920.png"
