---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Untitled spreadsheet - Sheet2/Untitled spreadsheet - Sheet2.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/204681/master/file/figures/Untitled%20spreadsheet%20-%20Sheet2/Untitled%20spreadsheet%20-%20Sheet2.csv"
    folder_url: "/users/87737/articles/204681/master/folder/figures/Untitled spreadsheet
      - Sheet2"
    treatFirstLineAsHeader: true
